# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 676b86d9ba1fc0499bfa78dcc3b4f556d04954766619a33bbf7196da9230b9bd5cd6c7b85b2064af9d34e26c45860c0a4d3139274f017b0f372cf0e7c71a3e99

test:
  secret_key_base: bc05dde5063fd07bc43f4b618f3b16ff64724a9d8f9225e5da0fb40f80aa73c33967fab12d2830610f2436b8ae81ac3fe98d9889413ab578d7e16be7475b3c29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
